name: Compile

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout V
        uses: actions/checkout@v2
        with:
          repository: vlang/v
      - name: Checkout Triangoli
        uses: actions/checkout@v2
        with:
          path: triangoli
      - name: Build V
        run: make
      - name: Build Triangoli
        run: |
          cd triangoli
          ../v -prod -skip-unused -show-timings main.v
